// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

import * as Tea_app       from "bucklescript-tea/lib/es6/src/tea_app.js";
import * as Tea_cmd       from "bucklescript-tea/lib/es6/src/tea_cmd.js";
import * as Tea_sub       from "bucklescript-tea/lib/es6/src/tea_sub.js";
import * as Overbots_view from "./overbots_view.js";

function init() {
  return /* tuple */[
          /* record */[/* notUsedYet */42],
          Tea_cmd.none
        ];
}

function update(model, _) {
  return /* tuple */[
          model,
          Tea_cmd.none
        ];
}

function subscriptions() {
  return Tea_sub.none;
}

var partial_arg = /* record */[
  /* init */init,
  /* update */update,
  /* view */Overbots_view.view,
  /* subscriptions */subscriptions
];

function main(param, param$1) {
  return Tea_app.standardProgram(partial_arg, param, param$1);
}

export {
  init          ,
  update        ,
  subscriptions ,
  main          ,
  
}
/* No side effect */
