// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

import * as $$Map    from "bs-platform/lib/es6/map.js";
import * as $$Set    from "bs-platform/lib/es6/set.js";
import * as Curry    from "bs-platform/lib/es6/curry.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";

var compare = Caml_obj.caml_compare;

var ResourceMap = $$Map.Make(/* module */[/* compare */compare]);

var compare$1 = Caml_obj.caml_compare;

var BoolFlagSet = $$Set.Make(/* module */[/* compare */compare$1]);

var init_bool_flags = BoolFlagSet[/* empty */0];

var compare$2 = Caml_obj.caml_compare;

var IntFlagMap = $$Map.Make(/* module */[/* compare */compare$2]);

var init_int_flags = Curry._3(IntFlagMap[/* add */3], /* NoIntFlagsYet */0, 0, IntFlagMap[/* empty */0]);

var nothingYet = /* NothingYet */0;

export {
  nothingYet      ,
  ResourceMap     ,
  BoolFlagSet     ,
  init_bool_flags ,
  IntFlagMap      ,
  init_int_flags  ,
  
}
/* ResourceMap Not a pure module */
