// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

import * as Tea_html from "bucklescript-tea/lib/es6/src/tea_html.js";

function view_container(enabled, id, title, children) {
  if (enabled) {
    return Tea_html.div(/* None */0, /* None */0, /* :: */[
                Tea_html.class$prime("container container-" + id),
                /* [] */0
              ], /* :: */[
                Tea_html.div(/* None */0, /* None */0, /* :: */[
                      Tea_html.class$prime("title"),
                      /* [] */0
                    ], /* :: */[
                      Tea_html.text(title),
                      /* [] */0
                    ]),
                /* :: */[
                  Tea_html.div(/* None */0, /* None */0, /* :: */[
                        Tea_html.class$prime("scroller " + id),
                        /* [] */0
                      ], children),
                  /* [] */0
                ]
              ]);
  } else {
    return Tea_html.noNode;
  }
}

function view_resources() {
  return /* [] */0;
}

function view_buttons() {
  return /* [] */0;
}

function view_scanner() {
  return /* [] */0;
}

function view_msgs() {
  return /* [] */0;
}

function view() {
  return Tea_html.div(/* None */0, /* None */0, /* :: */[
              Tea_html.class$prime("overbots"),
              /* [] */0
            ], /* :: */[
              Tea_html.div(/* None */0, /* None */0, /* :: */[
                    Tea_html.class$prime("header"),
                    /* [] */0
                  ], /* :: */[
                    Tea_html.text("OverBots"),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.div(/* None */0, /* None */0, /* :: */[
                      Tea_html.class$prime("body"),
                      /* [] */0
                    ], /* :: */[
                      view_container(/* true */1, "resources", "Resources", /* [] */0),
                      /* :: */[
                        view_container(/* true */1, "actions", "Actions", /* [] */0),
                        /* :: */[
                          view_container(/* true */1, "scanner", "Scanner", /* [] */0),
                          /* [] */0
                        ]
                      ]
                    ]),
                /* :: */[
                  view_container(/* true */1, "msgs", "Messages", /* [] */0),
                  /* [] */0
                ]
              ]
            ]);
}

export {
  view_container ,
  view_resources ,
  view_buttons   ,
  view_scanner   ,
  view_msgs      ,
  view           ,
  
}
/* No side effect */
