// Generated by BUCKLESCRIPT VERSION 1.7.5, PLEASE EDIT WITH CARE
'use strict';

import * as List                  from "bs-platform/lib/es6/list.js";
import * as Tea_cmd               from "bucklescript-tea/lib/es6/src/tea_cmd.js";
import * as Overbots_actions      from "./overbots_actions.js";
import * as Overbots_transformers from "./overbots_transformers.js";

function pruneOldMsgs(msgs) {
  var _i = 20;
  var _acc = /* [] */0;
  var _param = msgs;
  while(true) {
    var param = _param;
    var acc = _acc;
    var i = _i;
    if (param) {
      if (i) {
        _param = param[1];
        _acc = /* :: */[
          param[0],
          acc
        ];
        _i = i - 1 | 0;
        continue ;
        
      } else {
        return List.rev(acc);
      }
    } else {
      return List.rev(acc);
    }
  };
}

function update_state(model, new_time) {
  var time = new_time - model[/* start_realtime */0];
  var match = Overbots_actions.update_timeactions(model, time);
  var match$1 = Overbots_transformers.update_transformations(match[0], time);
  var model$1 = match$1[0];
  var msgs = pruneOldMsgs(model$1[/* msgs */3]);
  var model_000 = /* start_realtime */model$1[/* start_realtime */0];
  var model_004 = /* resource_values */model$1[/* resource_values */4];
  var model_005 = /* bool_flags */model$1[/* bool_flags */5];
  var model_006 = /* int_flags */model$1[/* int_flags */6];
  var model_007 = /* float_flags */model$1[/* float_flags */7];
  var model_008 = /* cache */model$1[/* cache */8];
  var model$2 = /* record */[
    model_000,
    /* current_realtime */new_time,
    /* gametime */time,
    /* msgs */msgs,
    model_004,
    model_005,
    model_006,
    model_007,
    model_008
  ];
  return /* tuple */[
          model$2,
          Tea_cmd.batch(/* :: */[
                match[1],
                /* :: */[
                  match$1[1],
                  /* [] */0
                ]
              ])
        ];
}

var max_msg_count = 20;

export {
  max_msg_count ,
  pruneOldMsgs  ,
  update_state  ,
  
}
/* Overbots_actions Not a pure module */
