// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

import * as $$Map    from "bs-platform/lib/es6/map.js";
import * as $$Set    from "bs-platform/lib/es6/set.js";
import * as Block    from "bs-platform/lib/es6/block.js";
import * as Curry    from "bs-platform/lib/es6/curry.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";

function timeMsg(param_0, param_1) {
  return /* TimeMsg */[
          param_0,
          param_1
        ];
}

var compare = Caml_obj.caml_compare;

var ResourceMap = $$Map.Make(/* module */[/* compare */compare]);

var compare$1 = Caml_obj.caml_compare;

var BoolFlagSet = $$Set.Make(/* module */[/* compare */compare$1]);

var init_bool_flags = BoolFlagSet[/* empty */0];

var compare$2 = Caml_obj.caml_compare;

var IntFlagMap = $$Map.Make(/* module */[/* compare */compare$2]);

var init_int_flags = Curry._3(IntFlagMap[/* add */3], /* TimeActionIdx */0, 0, IntFlagMap[/* empty */0]);

var compare$3 = Caml_obj.caml_compare;

var FloatFlagMap = $$Map.Make(/* module */[/* compare */compare$3]);

var init_float_flags = Curry._3(FloatFlagMap[/* add */3], /* BasicSolarPanelSelfGeneration */0, 0.0, FloatFlagMap[/* empty */0]);

function updateFrame(param_0) {
  return /* UpdateFrame */Block.__(0, [param_0]);
}

function actionButtonClicked(param_0) {
  return /* ActionButtonClicked */Block.__(1, [param_0]);
}

function loadData(param_0) {
  return /* LoadData */Block.__(2, [param_0]);
}

function transformers(param) {
  return param[/* transformers */0];
}

function resource_deltas(param) {
  return param[/* resource_deltas */1];
}

function start_realtime(param) {
  return param[/* start_realtime */0];
}

function current_realtime(param) {
  return param[/* current_realtime */1];
}

function gametime(param) {
  return param[/* gametime */2];
}

function msgs(param) {
  return param[/* msgs */3];
}

function resource_values(param) {
  return param[/* resource_values */4];
}

function bool_flags(param) {
  return param[/* bool_flags */5];
}

function int_flags(param) {
  return param[/* int_flags */6];
}

function float_flags(param) {
  return param[/* float_flags */7];
}

function cache(param) {
  return param[/* cache */8];
}

var energy = /* Energy */0;

var ironOxide = /* IronOxide */1;

var rawSilicon = /* RawSilicon */2;

var internalPowerEnabled = /* InternalPowerEnabled */0;

var solarPanelsReadyToUnfold = /* SolarPanelsReadyToUnfold */1;

var solarPanelsGenerating = /* SolarPanelsGenerating */2;

var drillDeployed = /* DrillDeployed */3;

var timeActionIdx = /* TimeActionIdx */0;

var saveData = /* SaveData */0;

export {
  timeMsg                  ,
  energy                   ,
  ironOxide                ,
  rawSilicon               ,
  ResourceMap              ,
  internalPowerEnabled     ,
  solarPanelsReadyToUnfold ,
  solarPanelsGenerating    ,
  drillDeployed            ,
  BoolFlagSet              ,
  init_bool_flags          ,
  timeActionIdx            ,
  IntFlagMap               ,
  init_int_flags           ,
  FloatFlagMap             ,
  init_float_flags         ,
  updateFrame              ,
  actionButtonClicked      ,
  loadData                 ,
  saveData                 ,
  transformers             ,
  resource_deltas          ,
  start_realtime           ,
  current_realtime         ,
  gametime                 ,
  msgs                     ,
  resource_values          ,
  bool_flags               ,
  int_flags                ,
  float_flags              ,
  cache                    ,
  
}
/* ResourceMap Not a pure module */
