// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

import * as $$Map    from "bs-platform/lib/es6/map.js";
import * as $$Set    from "bs-platform/lib/es6/set.js";
import * as Block    from "bs-platform/lib/es6/block.js";
import * as Curry    from "bs-platform/lib/es6/curry.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";

var compare = Caml_obj.caml_compare;

var ResourceMap = $$Map.Make(/* module */[/* compare */compare]);

var compare$1 = Caml_obj.caml_compare;

var BoolFlagSet = $$Set.Make(/* module */[/* compare */compare$1]);

var init_bool_flags = BoolFlagSet[/* empty */0];

var compare$2 = Caml_obj.caml_compare;

var IntFlagMap = $$Map.Make(/* module */[/* compare */compare$2]);

var init_int_flags = Curry._3(IntFlagMap[/* add */3], /* TimeActionIdx */0, 0, IntFlagMap[/* empty */0]);

var compare$3 = Caml_obj.caml_compare;

var FloatFlagMap = $$Map.Make(/* module */[/* compare */compare$3]);

var init_float_flags = Curry._3(FloatFlagMap[/* add */3], /* BasicSolarPanelSelfGeneration */0, 0.0, FloatFlagMap[/* empty */0]);

function updateFrame(param_0) {
  return /* UpdateFrame */Block.__(0, [param_0]);
}

function actionButtonClicked(param_0) {
  return /* ActionButtonClicked */Block.__(1, [param_0]);
}

export {
  ResourceMap         ,
  BoolFlagSet         ,
  init_bool_flags     ,
  IntFlagMap          ,
  init_int_flags      ,
  FloatFlagMap        ,
  init_float_flags    ,
  updateFrame         ,
  actionButtonClicked ,
  
}
/* ResourceMap Not a pure module */
