// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

import * as Tea_app            from "bucklescript-tea/lib/es6/src/tea_app.js";
import * as Tea_cmd            from "bucklescript-tea/lib/es6/src/tea_cmd.js";
import * as Tea_sub            from "bucklescript-tea/lib/es6/src/tea_sub.js";
import * as Overbots_view      from "./overbots_view.js";
import * as Overbots_types     from "./overbots_types.js";
import * as Overbots_update    from "./overbots_update.js";
import * as Overbots_buttons   from "./overbots_buttons.js";
import * as Overbots_resource  from "./overbots_resource.js";
import * as Tea_animationframe from "bucklescript-tea/lib/es6/src/tea_animationframe.js";

function init() {
  var model = /* record */[
    /* start_realtime */-1.0,
    /* current_realtime */-1.0,
    /* gametime */0.0,
    /* msgs : [] */0,
    /* resource_values */Overbots_resource.init_resources_values,
    /* bool_flags */Overbots_types.init_bool_flags,
    /* int_flags */Overbots_types.init_int_flags,
    /* float_flags */Overbots_types.init_float_flags
  ];
  return /* tuple */[
          model,
          Tea_cmd.none
        ];
}

function update(model, param) {
  if (param.tag) {
    return Overbots_buttons.perform_button(model, param[0]);
  } else {
    var time = param[0][/* time */0] * 0.001;
    var model$1 = model[/* start_realtime */0] >= 0.0 ? model : /* record */[
        /* start_realtime */time,
        /* current_realtime */time,
        /* gametime */0.0,
        /* msgs */model[/* msgs */3],
        /* resource_values */model[/* resource_values */4],
        /* bool_flags */model[/* bool_flags */5],
        /* int_flags */model[/* int_flags */6],
        /* float_flags */model[/* float_flags */7]
      ];
    return Overbots_update.update_state(model$1, time);
  }
}

function subscriptions() {
  return Tea_sub.batch(/* :: */[
              Tea_animationframe.every(/* None */0, Overbots_types.updateFrame),
              /* [] */0
            ]);
}

var partial_arg = /* record */[
  /* init */init,
  /* update */update,
  /* view */Overbots_view.view,
  /* subscriptions */subscriptions
];

function main(param, param$1) {
  return Tea_app.standardProgram(partial_arg, param, param$1);
}

export {
  init          ,
  update        ,
  subscriptions ,
  main          ,
  
}
/* Overbots_view Not a pure module */
