// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

import * as Curry          from "bs-platform/lib/es6/curry.js";
import * as Overbots_types from "./overbots_types.js";

function bool_flag_exists(fid, model) {
  return Curry._2(Overbots_types.BoolFlagSet[/* mem */2], fid, model[/* bool_flags */5]);
}

function bool_flag_set(fid, model) {
  var bool_flags = Curry._2(Overbots_types.BoolFlagSet[/* add */3], fid, model[/* bool_flags */5]);
  var newrecord = model.slice();
  newrecord[/* bool_flags */5] = bool_flags;
  return newrecord;
}

function bool_flag_reset(fid, model) {
  var bool_flags = Curry._2(Overbots_types.BoolFlagSet[/* remove */5], fid, model[/* bool_flags */5]);
  var newrecord = model.slice();
  newrecord[/* bool_flags */5] = bool_flags;
  return newrecord;
}

function int_flag_value(fid, model) {
  return Curry._2(Overbots_types.IntFlagMap[/* find */21], fid, model[/* int_flags */6]);
}

function int_flag_set(fid, value, model) {
  var int_flags = Curry._3(Overbots_types.IntFlagMap[/* add */3], fid, value, model[/* int_flags */6]);
  var newrecord = model.slice();
  newrecord[/* int_flags */6] = int_flags;
  return newrecord;
}

function int_flag_add(fid, delta, model) {
  var value = delta + int_flag_value(fid, model) | 0;
  return int_flag_set(fid, value, model);
}

function float_flag_value(fid, model) {
  return Curry._2(Overbots_types.FloatFlagMap[/* find */21], fid, model[/* float_flags */7]);
}

function float_flag_set(fid, value, model) {
  var float_flags = Curry._3(Overbots_types.FloatFlagMap[/* add */3], fid, value, model[/* float_flags */7]);
  var newrecord = model.slice();
  newrecord[/* float_flags */7] = float_flags;
  return newrecord;
}

function float_flag_add(fid, delta, model) {
  var value = delta + float_flag_value(fid, model);
  return float_flag_set(fid, value, model);
}

export {
  bool_flag_exists ,
  bool_flag_set    ,
  bool_flag_reset  ,
  int_flag_value   ,
  int_flag_set     ,
  int_flag_add     ,
  float_flag_value ,
  float_flag_set   ,
  float_flag_add   ,
  
}
/* Overbots_types Not a pure module */
