// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

import * as List              from "bs-platform/lib/es6/list.js";
import * as Curry             from "bs-platform/lib/es6/curry.js";
import * as $$String          from "bs-platform/lib/es6/string.js";
import * as Tea_html          from "bucklescript-tea/lib/es6/src/tea_html.js";
import * as Pervasives        from "bs-platform/lib/es6/pervasives.js";
import * as Overbots_resource from "./overbots_resource.js";

function view_container(enabled, id, title, children) {
  if (enabled) {
    return Tea_html.div(/* None */0, /* None */0, /* :: */[
                Tea_html.class$prime("container container-" + id),
                /* [] */0
              ], /* :: */[
                Tea_html.div(/* None */0, /* None */0, /* :: */[
                      Tea_html.class$prime("title"),
                      /* [] */0
                    ], /* :: */[
                      Tea_html.text(title),
                      /* [] */0
                    ]),
                /* :: */[
                  Tea_html.div(/* None */0, /* None */0, /* :: */[
                        Tea_html.class$prime("scroller " + id),
                        /* [] */0
                      ], children),
                  /* [] */0
                ]
              ]);
  } else {
    return Tea_html.noNode;
  }
}

function format_value(value) {
  if (value < 10000.0) {
    var str = Pervasives.string_of_float(value);
    var str$1 = $$String.sub(str, 0, Pervasives.min(str.length, 6));
    return str$1 + $$String.make(6 - str$1.length | 0, /* "0" */48);
  } else {
    return Pervasives.string_of_int(value | 0);
  }
}

function view_resources_category_resource(model, param) {
  var rid = param[0];
  var r = Overbots_resource.get_resource_module(rid);
  if (Curry._1(r[/* shown */1], model)) {
    var value = format_value(Overbots_resource.get_resource_value(rid, model));
    return /* :: */[
            Tea_html.div(/* None */0, /* None */0, /* :: */[
                  Tea_html.class$prime("resource resource-" + param[2]),
                  /* [] */0
                ], /* :: */[
                  Tea_html.div(/* None */0, /* None */0, /* :: */[
                        Tea_html.class$prime("resource-name"),
                        /* [] */0
                      ], /* :: */[
                        Tea_html.text(param[1]),
                        /* [] */0
                      ]),
                  /* :: */[
                    Tea_html.div(/* None */0, /* None */0, /* :: */[
                          Tea_html.class$prime("resource-value"),
                          /* [] */0
                        ], /* :: */[
                          Tea_html.text(value),
                          /* [] */0
                        ]),
                    /* [] */0
                  ]
                ]),
            /* [] */0
          ];
  } else {
    return /* [] */0;
  }
}

function view_resources_categories(model, param) {
  var name = param[0];
  var children = List.flatten(List.map(function (param) {
            return view_resources_category_resource(model, param);
          }, param[2]));
  if (children) {
    var children$1 = name === "" ? children : /* :: */[
        Tea_html.div(/* None */0, /* None */0, /* :: */[
              Tea_html.class$prime("category-title"),
              /* [] */0
            ], /* :: */[
              Tea_html.text(name),
              /* [] */0
            ]),
        children
      ];
    return /* :: */[
            Tea_html.div(/* None */0, /* None */0, /* :: */[
                  Tea_html.class$prime("resource-category resource-category-" + param[1]),
                  /* [] */0
                ], children$1),
            /* [] */0
          ];
  } else {
    return /* [] */0;
  }
}

function view_resources(model) {
  return List.flatten(List.map(function (param) {
                  return view_resources_categories(model, param);
                }, Overbots_resource.displayed_resources));
}

function view_buttons() {
  return /* [] */0;
}

function view_scanner() {
  return /* [] */0;
}

function view_msgs() {
  return /* [] */0;
}

function view(model) {
  return Tea_html.div(/* None */0, /* None */0, /* :: */[
              Tea_html.class$prime("overbots"),
              /* [] */0
            ], /* :: */[
              Tea_html.div(/* None */0, /* None */0, /* :: */[
                    Tea_html.class$prime("header"),
                    /* [] */0
                  ], /* :: */[
                    Tea_html.text("OverBots"),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.div(/* None */0, /* None */0, /* :: */[
                      Tea_html.class$prime("body"),
                      /* [] */0
                    ], /* :: */[
                      view_container(/* true */1, "resources", "Resources", view_resources(model)),
                      /* :: */[
                        view_container(/* true */1, "actions", "Actions", /* [] */0),
                        /* :: */[
                          view_container(/* true */1, "scanner", "Scanner", /* [] */0),
                          /* [] */0
                        ]
                      ]
                    ]),
                /* :: */[
                  view_container(/* true */1, "msgs", "Messages", /* [] */0),
                  /* [] */0
                ]
              ]
            ]);
}

export {
  view_container                   ,
  format_value                     ,
  view_resources_category_resource ,
  view_resources_categories        ,
  view_resources                   ,
  view_buttons                     ,
  view_scanner                     ,
  view_msgs                        ,
  view                             ,
  
}
/* Overbots_resource Not a pure module */
