// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

import * as Curry          from "bs-platform/lib/es6/curry.js";
import * as Overbots_types from "./overbots_types.js";

function bool_flag_exists(fid, model) {
  return Curry._2(Overbots_types.BoolFlagSet[/* mem */2], fid, model[/* bool_flags */2]);
}

function int_flag_value(fid, model) {
  return Curry._2(Overbots_types.IntFlagMap[/* find */21], fid, model[/* int_flags */3]);
}

export {
  bool_flag_exists ,
  int_flag_value   ,
  
}
/* Overbots_types Not a pure module */
