// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

import * as Tea_app    from "bucklescript-tea/lib/es6/src/tea_app.js";
import * as Tea_cmd    from "bucklescript-tea/lib/es6/src/tea_cmd.js";
import * as Tea_sub    from "bucklescript-tea/lib/es6/src/tea_sub.js";
import * as Tea_html   from "bucklescript-tea/lib/es6/src/tea_html.js";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

function init() {
  return /* tuple */[
          /* record */[/* notUsedYet */42],
          Tea_cmd.none
        ];
}

function update(model, _) {
  return /* tuple */[
          model,
          Tea_cmd.none
        ];
}

function subscriptions() {
  return Tea_sub.none;
}

function view(model) {
  return Tea_html.div(/* None */0, /* None */0, /* [] */0, /* :: */[
              Tea_html.text(Pervasives.string_of_int(model[/* notUsedYet */0])),
              /* [] */0
            ]);
}

var partial_arg = /* record */[
  /* init */init,
  /* update */update,
  /* view */view,
  /* subscriptions */subscriptions
];

function main(param, param$1) {
  return Tea_app.standardProgram(partial_arg, param, param$1);
}

var nothingYet = /* NothingYet */0;

export {
  nothingYet    ,
  init          ,
  update        ,
  subscriptions ,
  view          ,
  main          ,
  
}
/* No side effect */
