// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

import * as Tea_cmd          from "bucklescript-tea/lib/es6/src/tea_cmd.js";
import * as Overbots_actions from "./overbots_actions.js";

function update_state(model, new_time) {
  var time = new_time - model[/* start_realtime */0];
  var match = Overbots_actions.update_timeactions(model, time);
  var newrecord = match[0].slice();
  newrecord[/* current_realtime */1] = new_time;
  newrecord[/* gametime */2] = time;
  return /* tuple */[
          newrecord,
          Tea_cmd.batch(/* :: */[
                match[1],
                /* [] */0
              ])
        ];
}

export {
  update_state ,
  
}
/* Overbots_actions Not a pure module */
